---
- hosts: all
  become: true
  tasks:

  - name: Setup bonding on inetRouter
    block:
      - name: Setup bond0
        template:
          src: inetRouter_ifcfg-bond0.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-bond0
          owner: root
          group: root
          mode: 0644
      - name: Setup eth1
        template:
          src: inetRouter_ifcfg-eth1.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth1
          owner: root
          group: root
          mode: 0644
      - name: Setup eth2
        template:
          src: inetRouter_ifcfg-eth2.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth2
          owner: root
          group: root
          mode: 0644
      - name: Restart network
        service:
          name: network
          state: restarted
          enabled: true
    when: (ansible_hostname == "inetRouter")

  - name: Setup bonding on centralRouter
    block:
      - name: Setup bond0
        template:
          src: centralRouter_ifcfg-bond0.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-bond0
          owner: root
          group: root
          mode: 0644
      - name: Setup eth1
        template:
          src: centralRouter_ifcfg-eth1.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth1
          owner: root
          group: root
          mode: 0644
      - name: Setup eth2
        template:
          src: centralRouter_ifcfg-eth2.j2
          dest: /etc/sysconfig/network-scripts/ifcfg-eth2
          owner: root
          group: root
          mode: 0644
      - name: Restart network
        service:
          name: network
          state: restarted
          enabled: true
    when: (ansible_hostname == "centralRouter")

  - name: set up route on testClient1
    template:
      src: testClient1_ifcfg-vlan1.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testClient1")

  - name: set up route on testClient2
    template:
      src: testClient2_50-cloud-init.yaml.j2
      dest: /etc/netplan/50-cloud-init.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testClient2")

  - name: set up route on testServer1
    template:
      src: testServer1_ifcfg-vlan1.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testServer1")

  - name: set up route on testServer2
    template:
      src: testServer2_50-cloud-init.yaml.j2
      dest: /etc/netplan/50-cloud-init.yaml
      owner: root
      group: root
      mode: 0644
    when: (ansible_hostname == "testServer2")

  - name: reboot hosts
    block:
    - shell: systemctl reboot
      async: 300
      poll: 0
      ignore_errors: true

    - name: wait for system to come back online
      wait_for_connection:
        delay: 60
        timeout: 300
