---
# defaults file for web
#confluence_version: '8.9.7'
confluence_archive_name: 'atlassian-confluence-{{ confluence_version }}.tar.gz'
confluence_download_url: 'https://www.atlassian.com/software/confluence/downloads/binary'
confluence_checksum_url: '{{ confluence_download_url }}/{{ confluence_archive_name }}.sha256'
confluence_download_path: '/tmp'

# The Confluence user and group
confluence_user: 'confluence'
confluence_group: '{{ confluence_user }}'

# The Confluence directories
confluence_install_path: '/opt/atlassian/confluence'
confluence_home_path: '/var/atlassian/application-data/confluence'

# The Confluence environment configuration
confluence_jvm_minimum_memory: '1024m'
confluence_jvm_maximum_memory: '1024m'

# The Confluence database connection settings
confluence_db_configuration: false
confluence_db_host: ''
confluence_db_port: ''
confluence_db_name: ''
confluence_db_username: ''
confluence_db_password: ''

# The Confluence proxy settings
confluence_tomcat_connector_proxyname: ''
confluence_tomcat_connector_scheme: 'http'
confluence_tomcat_connector_proxyport: "{{ (confluence_tomcat_connector_scheme | lower == 'http') | ternary('80', '443') }}"

# defaults file for roles/ssl-certificates
# Text content of the public certificate
ssl_certificate_public_content: 'Confluence'

# Server path to SSL public certificate
ssl_certificate_public_path: /etc/nginx/ssl/confluence.crt
# Server path to SSL certificate key
ssl_certificate_key_path: /etc/nginx/ssl/confluence.key

# Create a self-signed certificate if necessary
ssl_certificate_selfsigned_create: true

# Certificate subject
ssl_certificate_selfsigned_subject: |-
  /C=RU/ST=Russian/L=Moscow/O=Home/CN=confluence.home.ru

# Certificate validity (days)
ssl_certificate_selfsigned_days: 365

# Whether or not to install OpenSSL
ssl_certificate_install_openssl: true

## defaults settings for roles UFW
ufw_allowed_ports:
  - 22
  - 80
  - 443
  - 514
  - 5432
  - 8000
  - 8090
  - 9100
