
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202404.26.0"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.gui = true
    vmware.memory = 1024
    vmware.cpus = 2
    vmware.ssh_info_public = true
    vmware.linked_clone = false
    end

    config.vm.define "nfss" do |nfss|
      nfss.vm.network "private_network", ip: "192.168.65.10", vmware__intnet: "vmxnet"
      nfss.vm.hostname = "nfss"
      end

    config.vm.define "nfsc" do |nfsc|
      nfsc.vm.network "private_network", ip: "192.168.65.11", vmware__intnet: "vmxnet"
      nfsc.vm.hostname = "nfsc"
      end
    end
