---
# defaults file for psqlslave
repmgr_user: 'repmgr'
repmgr_password: 'P@ssw0rd'
repmgr_db: 'repmgr'
replicator_user: 'replication'
replicator_password: 'P@ssw0rd'
master_ip: '192.168.255.30'
slave_ip: '192.168.255.31'

## defaults settings for roles UFW
ufw_allowed_ports:
  - 22
  - 80
  - 53
  - 443
  - 514
  - 1514
  - 5432
  - 9100
  - 9187
