Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202404.26.0"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.gui = true
    vmware.memory = 4096
    vmware.cpus = 2
    vmware.ssh_info_public = true
    vmware.linked_clone = false
    end

    config.vm.define "rsyslog" do |rsyslog|
      rsyslog.vm.network "private_network", ip: "192.168.65.10", vmware__intnet: "vmxnet"
      rsyslog.vm.hostname = "rsyslog"
      end

    config.vm.define "web" do |web|
      web.vm.network "private_network", ip: "192.168.65.11", vmware__intnet: "vmxnet"
      web.vm.hostname = "web"
      end

#    config.vm.define "elk" do |elk|
#      elk.vm.network "private_network", ip: "192.168.65.12", vmware__intnet: "vmxnet"
#      elk.vm.hostname = "elk"
#      end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "log.yml"
      ansible.become = true
      ansible.limit = "all"
      ansible.host_key_checking = "false"
      ansible.groups = {
          "web" => ["web"],
          "rsyslog" => ["rsyslog"]
        }
      end
    end
