---
# handlers file for Router
- name: Start haproxy
  service:
    name: nginx
    state: started

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: systemd reload
  systemd:
    daemon_reload: yes

- name: rsyslog restart
  systemd:
    name: rsyslog
    state: restarted
