---
# tasks file for psqlmaster
- name: Prepare For Install Psqlmaster
  include_tasks: tasks/prepare.yml

- name: Prepare For Setting Psqlmaster
  include_tasks: tasks/setting_posgresql.yml

- name: Install UFW
  include_tasks: tasks/setting_ufw.yml

- name: Install Node_exporter
  include_tasks: tasks/install_node_exporter.yml
