- name: Create a Superuser PostgreSQL database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ replicator_user }}"
    password: "{{ replicator_password }}"
    role_attr_flags: REPLICATION
    encrypted: yes
    state: present

- name: Create barman user
  become: yes
  become_user: postgres
  postgresql_user:
    name: barman
    password: '{{ barman_user_password }}'
    role_attr_flags: SUPERUSER
    #ignore_errors: true

- name: "Create nextcloud database"
  become: yes
  become_user: postgres
  postgresql_db:
    state: present
    name: "{{ db_name }}"

    #  - name: Create DB for backup
    #    become_user: postgres
    #    postgresql_db:
    #      name: nextcloud
    #      encoding: UTF-8
    #      template: template0
    #      state: present

    #  - name: Create db user
    #    community.postgresql.postgresql_user:
    #      state: present
    #      name: "{{ db_user }}"
    #      password: "{{ db_password }}"
    #    become: true
    #    become_user: postgres


- name: "Create db user"
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_password }}"
    role_attr_flags: SUPERUSER
    state: present

- name: "Grant db user access to app db"
  become: yes
  become_user: postgres
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ nextcloud_db_user }}"
    grant_option: yes
    privs: all

    #  - name: Create nextcloud user
      #  become: yes
      #  become_user: postgres
      #  postgresql_user:
      #    name: admcloud
      #    password: '{{ admcloud_user_password }}'
      #    role_attr_flags: NOSUPERUSER

- name: copy postgresql.conf
  template:
    src: postgresql_master.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: copy pg_hba.conf
  template:
    src: pg_hba_master.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: Restart Postgresql
  systemd:
    name: postgresql
    state: restarted
