- name: copy postgresql.conf
  template:
    src: postgresql_master.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: copy pg_hba.conf
  template:
    src: pg_hba_master.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: Restart Postgresql
  systemd:
    name: postgresql
    state: restarted

- name: Create a Superuser PostgreSQL database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ replicator_user }}"
    password: "{{ replicator_password }}"
    role_attr_flags: REPLICATION
    encrypted: yes
    #state: present

- name: Create barman user
  become: yes
  become_user: postgres
  postgresql_user:
    name: barman
    password: '{{ barman_user_password }}'
    role_attr_flags: SUPERUSER

- name: Create stream_barman user
  become: yes
  become_user: postgres
  postgresql_user:
    name: stream_barman_user
    password: '{{ stream_barman_user_pass }}'
    role_attr_flags: REPLICATION

- name: "Create barman database"
  become: yes
  become_user: postgres
  postgresql_db:
    state: present
    name: "barman"

- name: "Create nextcloud database"
  become: yes
  become_user: postgres
  postgresql_db:
    state: present
    name: "{{ db_name }}"

#- name: "Create replication database"
#  become: yes
#  become_user: postgres
#  postgresql_db:
#    state: present
#    name: "replication"

#- name: GRANT ALL PRIVILEGES ON DATABASE
#  postgresql_privs:
#    db: replication
#    privs: ALL
#    type: database
#    role: replication

- name: GRANT ALL PRIVILEGES ON DATABASE nextcloud
  postgresql_privs:
    db: nextcloud
    privs: ALL
    type: database
    role: postgres

- name: GRANT ALL PRIVILEGES ON DATABASE barman
  postgresql_privs:
    db: barman
    privs: ALL
    type: database
    role: barman

- name: Restore dump base nextcloud
  postgresql_db:
    name: nextcloud
    login_user: postgres
    login_password: 'P@ssw0rd'
    state: restore
    target: '/mnt/backup/psqlmaster/psqlmaster_alldump.sql'


#- name: "Create db user"
#  become: yes
#  become_user: postgres
#  postgresql_user:
#    name: "{{ nextcloud_db_user }}"
#    password: "{{ nextcloud_db_password }}"
#    role_attr_flags: SUPERUSER
#    state: present

#- name: "Grant db user access to app db"
#  become: yes
#  become_user: postgres
#  postgresql_privs:
#    type: database
#    database: "{{ db_name }}"
#    roles: "{{ nextcloud_db_user }}"
#    grant_option: yes
#    privs: all

#- name: copy postgresql.conf
#  template:
#    src: postgresql_master_replica.conf.j2
#    dest: /etc/postgresql/16/main/postgresql.conf
#    owner: postgres
#    group: postgres
#    mode: '0600'


- name: Restart Postgresql
  systemd:
    name: postgresql
    state: restarted
