- name: Copy multiple files in Ansible with different permissions
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/00-installer-config.yaml.j2', dest: '/etc/netplan/00-installer-config.yaml'}
    - { src: 'templates/50-vagrant.yaml.j2', dest: '/etc/netplan/50-vagrant.yaml'}

- name: set permission to folder
  file:
    dest: /etc/netplan
    recurse: yes
    mode: '0600'

- name: Apply netplan
  command: sudo netplan apply
  async: 45
  poll: 0

- name: update
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: install app
  apt:
    name: openvswitch-switch-dpdk
    state: latest

- name: Apply netplan
  command: sudo netplan apply
  async: 45
  poll: 0

- name: Install required packages
  apt:
    name:
      - python3-psycopg2
      - acl
    state: latest

- name: Set up Postgres repo
  shell: |
   sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Download PostgreSQL key and add it to system keyring
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    #url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  #  state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install PostgreSQL
  apt:
    name:
      - postgresql-16
      - postgresql-contrib-16
      - barman-cli
    #state: present
    #update_cache: true

- name: copy all_log.conf
  template:
    src: all_log.conf
    dest: /etc/rsyslog.d/all_log.conf
    mode: '0755'
  notify:
    - rsyslog restart
