MACHINES = {
  :"docker" => {
              :box_name => "takesako/alpine-standard-v3.19",
              #:box_version => "2023.11.17",
              :ip_addr => '192.168.65.180',
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      config.vm.provider :vmware_desktop do |vmware|
        vmware.gui = true
        vmware.memory = 1024
        vmware.cpus = 2
        #vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
        vmware.ssh_info_public = true
        vmware.linked_clone = false
      end

      box.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
      apk add docker docker-compose
      rc-update add docker
      service docker start
    	  SHELL
          end
        end
      end
