---

- name: Install NFS
  package:
    name: nfs-common
    state: present

- name: Mount an NFS volume
  ansible.posix.mount:
    src: 192.168.255.22:/srv/nfs
    path: /mnt
    opts: vers=3,auto
    state: mounted
    fstype: nfs
