---
# tasks file for barman

- name: Prepare For Install Barman
  include_tasks: tasks/prepare.yml

- name: Prepare For Setting Barman
  include_tasks: tasks/setting_barman.yml

- name: Install UFW
  include_tasks: tasks/setting_ufw.yml

- name: Install Node_exporter
  include_tasks: tasks/install_node_exporter.yml
