---
# tasks file for web

- name: Install Nginx
  apt:
    name: nginx
    state: latest
  notify:
    - restart nginx

- name: Create NGINX config file from template
  template:
    src: templates/confluence.j2
    dest: /etc/nginx/sites-available/confluence

- name: Remove default uplink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable Nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started
  notify:
    - reload nginx
