---
# tasks file for web

- name: Install Nginx
  apt:
    name: nginx
    state: latest
  notify: restart nginx

- name: Create NGINX config file from template
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/nginx.conf.j2', dest: '/etc/nginx/nginx.conf'}
    - { src: 'templates/http.conf.j2', dest: '/etc/nginx/conf.d/http.conf'}
    - { src: 'templates/nextcloud.conf.j2', dest: '/etc/nginx/conf.d/nextcloud.conf'}

- name: Remove default uplink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable Nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
