---
# tasks file for web
- name: Prepare For Install Web
  include_tasks: tasks/prepare.yml

- name: Prepare For Install PHP
  include_tasks: tasks/install_php.yml

- name: Install UFW
  include_tasks: tasks/setting_ufw.yml

- name: Install SSL
  include_tasks: tasks/install_ssl.yml

- name: Install Nginx
  include_tasks: tasks/install_nginx.yml

- name: Install Nextcloud
  include_tasks: tasks/download_nc.yml

- name: Install Node_exporter
  include_tasks: tasks/install_node_exporter.yml
