- name: Create directories for Log file
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - '/var/log/dnsmasq'

- name: Install DNSmasq
  package:
    name: dnsmasq
    state: present

- name: Create NGINX config file from template
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/dnsmasq_addresses.j2', dest: '/etc/dnsmasq.d/dnsmasq_addresses'}
    - { src: 'templates/dnsmasq_cache.j2', dest: '/etc/dnsmasq.d/dnsmasq_cache'}
    - { src: 'templates/dnsmasq_hosts.j2', dest: '/etc/dnsmasq.d/dnsmasq_hosts'}
    - { src: 'templates/dnsmasq_logs.j2', dest: '/etc/dnsmasq.d/dnsmasq_logs'}
    - { src: 'templates/dnsmasq_forwards.j2', dest: '/etc/dnsmasq.d/dnsmasq_forwards'}

- name: Disble systemd-resolved service
  systemd:
    name: systemd-resolved
    daemon_reload: yes
    enabled: no
    state: stopped

- name: Enable DNSmasq service
  systemd:
    name: dnsmasq
    daemon_reload: yes
    enabled: yes
    state: started

- name: restart DNSmasq
  service:
    name: dnsmasq
    state: restarted
  become: yes
