---
# tasks file for Router

    - name: Copy files in Ansible with different permissions
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: 'templates/50-vagrant.yaml.j2', dest: '/etc/netplan/50-vagrant.yaml'}

    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    - name: set permission to folder
      file:
        dest: /etc/netplan
        recurse: yes
        mode: '0600'

    - name: Apply netplan
      command: sudo netplan apply
      async: 45
      poll: 0

    - name: update
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Set timezone to Europe/Moscow
      timezone:
        name: Europe/Moscow

    - name: install app
      apt:
        name: openvswitch-switch-dpdk
        state: latest

    - name: Apply netplan
      command: sudo netplan apply
      async: 45
      poll: 0

    - name: copy all_log.conf
      template:
        src: templates/all_log.conf
        dest: /etc/rsyslog.d/all_log.conf
        mode: '0755'
      notify:
        - rsyslog restart
