---
- name: Create User Node_exporter
  user:
    name: nogroup
    create_home: no
    shell: /bin/false

- name: Install DNSmasq
  package:
    name: nfs-kernel-server
    state: present

- name: Create directories for NFS
  file:
    path: "{{ item }}"
    state: directory
    owner: nogroup
    group: nogroup
  loop:
    - '/srv/nfs'
    - '/srv/nfs/nextcloud/'
    - '/srv/nfs/nextcloud/data'
    - '/srv/nfs/backup/'
    - '/srv/nfs/scripts/'


#- name: Create directories for NFS
#  file:
#    path: "{{ item }}"
#    state: directory
    #owner: vagrant
    #group: vagrant
#  loop:
#    - '/home/vagrant/scripts'

#- name: Setting config.php
#  shell: |
#    chown -R nogroup:nogroup /srv/nfs/


- name: Copy multiple files in Ansible
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/nfs_exports.j2', dest: '/etc/exports'}
    - { src: 'templates/rsync_nextcloud_data.sh.j2', dest: '/srv/nfs/scripts/rsync_nextcloud_data.sh'}

- name: Setting config.php
  shell: |
    chown -R nogroup:nogroup /srv/nfs
    chmod +x /srv/nfs/scripts/rsync_nextcloud_data.sh
    exportfs -s
