# tasks file for nfs

- name: Prepare For Install NFS
  include_tasks:
    file: prepare.yml
    apply:
      tags: prepare
  tags: prepare

- name: Install NFS
  include_tasks:
    file: install_nfssrv.yml
    apply:
      tags: nfs
  tags: nfs

- name: Install UFW
  include_tasks:
    file: setting_ufw.yml
    apply:
      tags: ufw
  tags: ufw

- name: Install Node_exporter
  include_tasks:
    file: install_node_exporter.yml
    apply:
      tags: node_exporter
  tags: node_exporter

- name: Setting Crontab
  include_tasks:
    file: setting_crontab.yml
    apply:
      tags: crontab
  tags: crontab
