
#- name: Create directories
#  file:
#    path: "/home/vagrant/scripts/"
#    state: directory
#    owner: vagrnat
#    group: vagrnat

- name: Copy multiple files in Ansible with different permissions
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/rsync_nextcloud_data.sh.j2', dest: '/srv/nfs/scripts/rsync_nextcloud_data.sh'}

- name: Creates a cron file under /etc/cron.d
  cron:
    name: rsync nextcloud data
    minute: "0/30"
    user: vagrant
    job: "/srv/nfs/scripts/rsync_nextcloud_data.sh"
