---
# defaults file for srvmon
# defaults file for roles/ssl-certificates
# Text content of the public certificate

# Server path to SSL public certificate
ssl_certificate_public_path_prom: /etc/nginx/ssl/prometheus.crt
# Server path to SSL certificate key
ssl_certificate_key_path_prom: /etc/nginx/ssl/prometheus.key

# Create a self-signed certificate if necessary
ssl_certificate_selfsigned_create: true

# Certificate subject
ssl_certificate_selfsigned_subject_prom: |-
  /C=RU/ST=Russian/L=Moscow/O=Home/OU=ITHome/CN=prometheus.home.ru

# Certificate validity (days)
ssl_certificate_selfsigned_days: 365

# Whether or not to install OpenSSL
ssl_certificate_install_openssl: true

# Server path to SSL public certificate
ssl_certificate_public_path_graf: /etc/nginx/ssl/grafana.crt
# Server path to SSL certificate key
ssl_certificate_key_path_graf: /etc/nginx/ssl/grafana.key
# Certificate subject
ssl_certificate_selfsigned_subject_graf: |-
  /C=RU/ST=Russian/L=Moscow/O=Home/OU=ITHome/CN=grafana.home.ru

# Server path to SSL public certificate
ssl_certificate_public_path_altman: /etc/nginx/ssl/alertmanager.crt
# Server path to SSL certificate key
ssl_certificate_key_path_altman: /etc/nginx/ssl/alertmanager.key
# Certificate subject
ssl_certificate_selfsigned_subject_altman: |-
  /C=RU/ST=Russian/L=Moscow/O=Home/OU=ITHome/CN=alertmanager.home.ru

ufw_allowed_ports:
  - 22
  - 80
  - 443
  - 514
  - 3000
  - 5432
  - 9090
  - 9093
  - 9094
  - 9100
