---
- name: Configure Router server
  hosts: router
  become: yes
  roles:
    - role: router

- name: Configure Web server
  hosts: web1
  become: yes
  roles:
    - role: web1

- name: Configure Web server
  hosts: web2
  become: yes
  roles:
    - role: web2

- name: Configure psqlmaster server
  hosts: psqlmaster
  become: yes
  roles:
    - role: psqlmaster

- name: Configure psqlslave server
  hosts: psqlslave
  become: yes
  roles:
    - role: psqlslave

- name: Configure srvmon server
  hosts: srvmon
  become: yes
  roles:
    - role: srvmon

- name: Configure barman server
  hosts: srvbackup
  become: yes
  roles:
    - role: srvbackup

- name: Configure nfs server
  hosts: nfs
  become: yes
  roles:
    - role: nfs
