---
- name: Required packages are installed
  package:
    name: "{{ redis_deps }}"
    state: present
  vars:
    redis_deps:
      - redis-server
      - "php{{ php_ver }}-redis"
  notify: Start redis

- name: Redis configuration is present
  template:
    src: templates/redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: 0640
  notify: Restart redis
