Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-stream-9"
  #config.vm.box_version = "2004.01"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.gui = true
    vmware.memory = 1024
    vmware.cpus = 2
    vmware.ssh_info_public = true
    vmware.linked_clone = false
    end

    config.vm.provision "ansible" do |ansible|
      #ansible.verbose = "vvv"
      ansible.playbook = "./provisioning/playbook.yml"
      ansible.become = "true"
    end

    config.vm.define "ns01" do |ns01|
      ns01.vm.network "private_network", ip: "192.168.50.10", vmware__intnet: "dns"
      ns01.vm.hostname = "ns01"
      end

    config.vm.define "client" do |client|
      client.vm.network "private_network", ip: "192.168.50.15", vmware__intnet: "dns"
      client.vm.hostname = "client"
      end
    end
