---
- name: Configure Router group hosts
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: Install iptables-persistent
      package:
        name: iptables-persistent
        state: present
        when: "'routers' in group_names"


    - name: Set up NAT on inetRouter
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_inetRouter.rules", dest: "/etc/iptables/rules.v4", mode: "0644" }
        - { src: "templates/iptables_restore_inetRouter", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")

    - name: Set up NAT on inetRouter2
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_inetrouter2.rules", dest: "/etc/iptables/rules.v4", mode: "0644" }
        - { src: "templates/iptables_restore_inetRouter2", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter2")

    - name:
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/knock.sh", dest: "/home/vagrant/knock.sh", mode: "0644" }
      when: (ansible_hostname == "centralRouter")

    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

- name: Configure Router group hosts
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: NGINX | Install NGINX
      apt:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
      when: (ansible_hostname == "centralServer")

    - name: Disable the ufw firewall.
      service:
        name: ufw
        state: stopped
        enabled: false
      when: (ansible_hostname == "centralServer")

    - name: disable default route
      template:
        src: templates/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: 0644
#      when: (ansible_hostname != "inetRouter")

    - name: add default gateway for centralRouter
      template:
        src: "50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

#    - name: restart all hosts
#      reboot:
