MACHINES = {
  :inetRouter => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "inetRouter",
        #:public => {:ip => "10.10.10.1", :adapter => 1},
        :net => [
                    #ip, adpter, netmask, virtualbox__intnet
                    ["192.168.255.1", 2, "255.255.255.252",  "router-net"],
                    ["192.168.50.10", 8, "255.255.255.0"],
                ]
  },

  :inetRouter2 => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "inetRouter2",
        :net => [
                    #ip, adpter, netmask, virtualbox__intnet
                    ["192.168.255.3", 2, "255.255.255.252",  "router-net"],
                    ["192.168.50.13", 8, "255.255.255.0"],
                ]
  },

  :centralRouter => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "centralRouter",
        :net => [
                   ["192.168.255.2",  2, "255.255.255.252",  "router-net"],
                   ["192.168.0.1",    3, "255.255.255.240",  "dir-net"],
                   ["192.168.50.11",  8, "255.255.255.0"],
                ]
  },

  :centralServer => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "centralServer",
        :net => [
                   ["192.168.0.2",    2, "255.255.255.240",  "dir-net"],
                   ["192.168.50.12",  8, "255.255.255.0"],
                ]
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo apt update
        #apt upgrade -y
        #sudo apt install traceroute -y
      SHELL
    end
  end
end
#      when "inetRouter"
#        box.vm.provision "shell", run: "always", inline: <<-SHELL
#        echo net.ipv4.conf.all.forwarding=1 >> /etc/sysctl.conf
#        sysctl -p /etc/sysctl.conf
#        iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
#        ip route add 192.168.0.0/16 via 192.168.255.2
#        run: "always",
#        inline: "route add default gw 192.168.0.1"
#        iptables-restore < /home/vagrant/iptables_inetRouter.rules
#        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
#        service sshd restart
#      SHELL

#      when "inetRouter2"
#        box.vm.network 'forwarded_port', guest: 8080, host: 8080, host_ip: '127.0.0.1'
#        box.vm.provision "shell", run: "always", inline: <<-SHELL
#        iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
#        ip route add 192.168.0.0/16 via 192.168.255.2
#      SHELL
