---
# tasks file for web

- name: Copy multiple files in Ansible with different permissions
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/00-installer-config.yaml.j2', dest: '/etc/netplan/00-installer-config.yaml'}
    - { src: 'templates/50-vagrant.yaml.j2', dest: '/etc/netplan/50-vagrant.yaml'}

- name: set permission to folder
  file:
    dest: /etc/netplan
    recurse: yes
    mode: '0600'

- name: Apply netplan
  command: sudo netplan apply
  async: 45
  poll: 0

- name: update
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: install app
  apt:
    name:
      - default-jdk
      - openvswitch-switch-dpdk
      - postgresql-client
    state: latest

- name: 'Ensure the dependencies are installed'
  package:
    name: 'tar'
    state: 'present'

- name: Apply netplan
  command: sudo netplan apply
  async: 45
  poll: 0

- name: copy all_log.conf
  template:
    src: all_log.conf
    dest: /etc/rsyslog.d/all_log.conf
    mode: '0755'
  notify:
    - rsyslog restart
