---

- name: Create User prometheus
  user:
    name: prometheus
    create_home: no
    shell: /bin/false

- name: Create directories for prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - '/tmp/prometheus'
    - '/etc/prometheus'
    - '/etc/prometheus/alerts_rules'
    - '/var/lib/prometheus'

- name: Download And Unzipped Prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz
    dest: /tmp/prometheus
    creates: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-arm64
    remote_src: yes

- name: Copy Bin Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-arm64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'prometheus', 'promtool' ]

- name: Copy Conf Files From Unzipped to Prometheus
  copy:
    src: /tmp/prometheus/prometheus-{{ prometheus_version }}.linux-arm64/{{ item }}
    dest: /etc/prometheus/
    remote_src: yes
    mode: preserve
    owner: prometheus
    group: prometheus
  loop: [ 'console_libraries', 'consoles', 'prometheus.yml' ]

- name: Remove prometheus archive files
  file:
    path: /tmp/prometheus
    state: absent

- name: Copy multiple files in Ansible for Prometheus
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/prometheus.yml.j2', dest: '/etc/prometheus/prometheus.yml'}
    - { src: 'templates/linux_host_rules.yml.j2', dest: '/etc/prometheus/alerts_rules/linux_host_rules.yml'}
    - { src: 'templates/prometheus.service.j2', dest: '/etc/systemd/system/prometheus.service'}
  notify:
    - systemd reload

- name: prometheus systemd
  systemd:
    name: prometheus
    enabled: yes
    state: started
