- name: Create directories for Grafana
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - '/tmp/grafana'

- name: Download Grafana from a file path
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_arm64.deb
    dest: /tmp/grafana/grafana_{{ grafana_version }}_arm64.deb
    #creates: /tmp/grafana/grafana_{{ grafana_version }}_arm64.deb

- name: Install a .deb package
  apt:
    deb: /tmp/grafana/grafana_{{ grafana_version }}_arm64.deb

- name: Remove Grafana archive files
  file:
    path: /tmp/grafana
    state: absent

- name: Copy multiple files in Ansible with different permissions
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/1860_rev37.json.j2', dest: '/etc/grafana/provisioning/dashboards/1860_rev37.json.j2'}

- name: Enable Grafana systemd
  systemd:
    name: grafana-server
    enabled: yes
    state: started
