---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create NGINX config file from template
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'templates/nginx.conf.j2', dest: '/etc/nginx/nginx.conf'}
    - { src: 'templates/prometheus.j2', dest: '/etc/nginx/sites-available/prometheus'}

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/prometheus
    dest: /etc/nginx/sites-enabled/prometheus
    state: link

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
  notify:
    - reload nginx
