---
# tasks file for srvmon

- name: Prepare For Install Prometheus
  include_tasks: tasks/prepare.yml

- name: Install UFW
  include_tasks: tasks/setting_ufw.yml

- name: Install SSL
  include_tasks: tasks/install_ssl.yml

- name: Install Nginx
  include_tasks: tasks/install_nginx.yml

- name: Install Prometheus
  include_tasks: tasks/install_prometheus.yml

- name: Install Alertmanager
  include_tasks: tasks/install_alertmanager.yml

- name: Install Node_exporter
  include_tasks: tasks/install_node_exporter.yml

- name: Install Grafana
  include_tasks: tasks/install_grafana.yml
