Vagrant.configure(2) do |config|

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "play.yml"
     ansible.inventory_path = "hosts"
   end

     config.vm.define "DynamicWeb" do |vmconfig|
      vmconfig.vm.box = 'bento/ubuntu-22.04'
      vmconfig.vm.network "private_network",
                     ip: "192.168.50.10",
                     adapter: 2
    vmconfig.vm.network "forwarded_port", guest: 8083, host: 8083
    vmconfig.vm.network "forwarded_port", guest: 8081, host: 8081
    vmconfig.vm.network "forwarded_port", guest: 8082, host: 8082
    vmconfig.vm.provider "virtualbox" do |vbx|
     vbx.memory = "4096"
     vbx.cpus = "2"
     vbx.customize ["modifyvm", :id, '--audio', 'none']
    end
   end

end
