- name: generate SSH key for postgres
  user:
    name: postgres
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    force: no
  when: (ansible_hostname == "psqlmaster")

#  Генерируем SSH-ключ для пользователя barman на хосте barman
- name: generate SSH key for barman
  user:
    name: barman
    uid: 994
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    force: no
  when: (ansible_hostname == "barman")

#  Забираем содержимое открытого ключа postgres c хоста master
- name: fetch all public ssh keys master
  shell: cat /var/lib/postgresql/.ssh/id_rsa.pub
  register: ssh_keys
  when: (ansible_hostname == "psqlmaster")

#  Копируем ключ с barman на master
- name: transfer public key to barman
  delegate_to: barman
  authorized_key:
    key: "{{ ssh_keys.stdout }}"
    comment: "{{ansible_hostname}}"
    user: barman
  when: (ansible_hostname == "psqlmaster")

#  Забираем содержимое открытого ключа barman c хоста barman
- name: fetch all public ssh keys barman
  shell: cat /var/lib/barman/.ssh/id_rsa.pub
  register: ssh_keys
  when: (ansible_hostname == "srvbackup")

#  Копируем ключ с master на barman
- name: transfer public key to barman
  delegate_to: psqlmaster
  authorized_key:
    key: "{{ ssh_keys.stdout }}"
    comment: "{{ansible_hostname}}"
    user: postgres
  when: (ansible_hostname == "srvbackup")

# Копируем файл .pgpass
- name: copy .pgpass
  template:
    src: .pgpass.j2
    dest: /var/lib/barman/.pgpass
    owner: barman
    group: barman
    mode: '0600'
  when: (ansible_hostname == "srvbackup")

# Копируем файл barman.conf
- name: copy barman.conf
  template:
    src: barman.conf.j2
    dest: /etc/barman.conf
    owner: barman
    group: barman
    mode: '0755'
  when: (ansible_hostname == "srvbackup")

# Копируем файл master.conf
- name: copy psqlmaster.conf
  template:
    src: psqlmaster.conf.j2
    dest: /etc/barman.d/psqlmaster.conf
    owner: barman
    group: barman
    mode: '0755'
  when: (ansible_hostname == "srvbackup")

- name: barman switch-wal psqlmaster
  become_user: barman
  shell: barman switch-wal psqlmaster
  when: (ansible_hostname == "srvbackup")

- name: barman cron
  become_user: barman
  shell: barman cron
  when: (ansible_hostname == "srvbackup")

- name: Switch-xlog force
  shell: barman switch-xlog --force --archive psqlmaster
  when: (ansible_hostname == "srvbackup")
