---
# handlers file for srvmon

- name: systemd reload
  systemd:
    daemon_reload: yes

- name: grafana systemd
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: rsyslog restart
  systemd:
    name: rsyslog
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: "Restart grafana"
  ansible.builtin.service:
    name: grafana-server
    state: restarted
  become: true
  listen: "restart_grafana"
  tags:
    - grafana_run

- name: "Set privileges on provisioned dashboards"
  ansible.builtin.file:
    path: "{{ grafana_data_dir }}/dashboards"
    recurse: true
    owner: "grafana"
    group: "grafana"
    mode: "0640"
  become: true
  listen: "provisioned dashboards changed"

- name: "Set privileges on provisioned dashboards directory"
  ansible.builtin.file:
    path: "{{ grafana_data_dir }}/dashboards"
    state: "directory"
    recurse: false
    mode: "0755"
  become: true
  listen: "provisioned dashboards changed"
